name: Docker Matrix Build and Publish

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - frontend
          - backend
          - api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.path }}
          file: ./${{ matrix.path }}/Dockerfile
          push: true
          tags: neeraja21/${{ matrix.path }}:latest
